package com.google.android.gms.internal;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;

public final class zzln<R extends Result>
  extends OptionalPendingResult<R>
{
  private final zzlc<R> zzacI;
  
  public zzln(PendingResult<R> paramPendingResult)
  {
    if (!(paramPendingResult instanceof zzlc)) {
      throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }
    this.zzacI = ((zzlc)paramPendingResult);
  }
  
  public R await()
  {
    return this.zzacI.await();
  }
  
  public R await(long paramLong, TimeUnit paramTimeUnit)
  {
    return this.zzacI.await(paramLong, paramTimeUnit);
  }
  
  public void cancel()
  {
    this.zzacI.cancel();
  }
  
  public R get()
  {
    if (isDone()) {
      return await(0L, TimeUnit.MILLISECONDS);
    }
    throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
  }
  
  public boolean isCanceled()
  {
    return this.zzacI.isCanceled();
  }
  
  public boolean isDone()
  {
    return this.zzacI.isReady();
  }
  
  public void setResultCallback(ResultCallback<? super R> paramResultCallback)
  {
    this.zzacI.setResultCallback(paramResultCallback);
  }
  
  public void setResultCallback(ResultCallback<? super R> paramResultCallback, long paramLong, TimeUnit paramTimeUnit)
  {
    this.zzacI.setResultCallback(paramResultCallback, paramLong, paramTimeUnit);
  }
  
  public void zza(PendingResult.zza paramzza)
  {
    this.zzacI.zza(paramzza);
  }
  
  public Integer zznF()
  {
    return this.zzacI.zznF();
  }
}


/* Location:              /Users/mohamedtajjiou/Downloads/Rerverse Engeneering/dex2jar-2.0/com.nianticlabs.pokemongo_0.47.1-2016111700_minAPI19(armeabi-v7a)(nodpi)_apkmirror.com (1)-dex2jar.jar!/com/google/android/gms/internal/zzln.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */